// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joorlevhixufgblcnsgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvb3JsZXZoaXh1ZmdibGNuc2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTE3ODIsImV4cCI6MjA2Njg2Nzc4Mn0.7IIrXvcZDFizCWu-c7jtbBxWaPnu7ReDosurl37Z6qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});